# Copyright (C) 2016 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
server:
  #port: 8080
  #port: 8081
  compression:
    enabled: true
    mime-types: application/hal+json
    min-response-size: 2KB
  error.whitelabel.enabled: false
  shutdown: graceful

spring:
  application.name: bestellung
  aop.proxy-target-class: false
  data.mongodb:
    authentication-database: admin
    auto-index-creation: false
    database: acme
    #host: localhost
    #port: 27017
    repositories.type: none
    username: admin
    uuid-representation: standard
  devtools.livereload.enabled: false
  jackson.default-property-inclusion: non_null
  lifecycle.timeout-per-shutdown-phase: 3s
  main:
    lazy-initialization: true
    web-application-type: reactive
  security.user.password: p
  spel.ignore: true

info.app:
  author: Juergen Zimmermann
  lecture: Softwarearchitektur
  semester: 3
  studiengang: Wirtschaftsinformatik und Microservices

management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-cloud-platform: kubernetes
management.endpoint.health:
  enabled: true
  probes.enabled: true
  show-details: ALWAYS
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 30s

---
spring:
  config.activate.on-profile: dev
  jackson.serialization.indent-output: true
  reactor.debugagent.enabled: true
